[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' https://eu.umami.is https://cdnjs.cloudflare.com https://static.cloudflareinsights.com;
  img-src 'self' https://res.cloudinary.com;
  connect-src 'self' https://ikaradimas.gr https://eu.umami.is;
  style-src 'self';
  font-src 'self';
  frame-src 'self';
"""
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"
Permissions-Policy = "geolocation=(self), microphone=()"
X-XSS-Protection = "1; mode=block"
